### ISSUE TITLE
Reduce RAM Footprint

### ISSUE THREAD

**Issue by Thyra** [NAMlab/streamlit_deepcre_app#13]
We're crashing the VM regularly because it's running out of memory so we need to find ways to be more memory-efficient. I'm thinking about smarter/smaller caching and potentially not even reading the full genomes if we know we only want a subset of genes in the first place (ugly code). I'll do some profiling and see what we can gain.

**Comment by PelFritz** [comment]
solved in 6defdd576a8768a05458e6c981217a570f779efb and afaf2a693635d78ffb477a549b5d78bc484b23dd
