### ISSUE TITLE
My pre-filtered VCF file is not loaded correctly

### ISSUE THREAD

**Issue by SMZmk** [NAMlab/streamlit_deepcre_app#26]
The vcf file:
#CHROM	POS	ID	REF	ALT
Chr1	4381569	AT1G12850	T	C
Chr1	4381553	AT1G12850	A	T
Chr1	4381542	AT1G12850	T	A
Chr1	4381533	AT1G12850	T	A
Chr1	4381498	AT1G12850	A	T

The list is empty after upload to the toolkit. 
What format doe I have to match?
Please add this to the description.

**Comment by PelFritz** [comment]
The VCF file has to be tab delimited. Is it tab delimited?

**Comment by SMZmk** [comment]
For Arabidopsis vcf files should not contain any chromosome name by plain numbers.

**Comment by PelFritz** [comment]
The chromosome names from Ensembl Plants are just numbers for Chromsomes 1 - 5. So if your chromsomes are Chr1 it won't match any chromosome names from Ensembl Plants

**Comment by SMZmk** [comment]
Maybe we should write this in the docu.
